/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package congwang.individual.UI;

import congwang.individual.clients.HelicopterClient;

/**
 * 
 * @author congwang
 */
public class UI extends javax.swing.JFrame {

	/**
	 * Creates new form UI
	 */
	public UI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jTextField2 = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		jTextField3 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		jTextArea2 = new javax.swing.JTextArea();
		jLabel5 = new javax.swing.JLabel();
		jComboBox1 = new javax.swing.JComboBox();
		jLabel6 = new javax.swing.JLabel();
		jTextField4 = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jTextField5 = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jComboBox2 = new javax.swing.JComboBox();
		jComboBox3 = new javax.swing.JComboBox();
		jDesktopPane1 = new javax.swing.JDesktopPane();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTable1 = new javax.swing.JTable();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();
		jLabel18 = new javax.swing.JLabel();
		jLabel19 = new javax.swing.JLabel();
		jLabel20 = new javax.swing.JLabel();
		jLabel21 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Please Choose Company");

		jLabel2.setText("Flight Number");

		jLabel3.setText("Flight Date");

		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField2ActionPerformed(evt);
			}
		});

		jLabel4.setText("Format 2012-12-21");

		jButton1.setText("Make booking request");

		jButton2.setText("Make cancel request");

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		jTextArea2.setColumns(20);
		jTextArea2.setRows(5);
		jScrollPane2.setViewportView(jTextArea2);

		jLabel5.setText("PassportNum");

		jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"CompanyA", "CompanyB", "CompanyC" }));

		jLabel6.setText("Ticket Number");

		jTextField4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField4ActionPerformed(evt);
			}
		});

		jLabel7.setText("PassportNum");

		jTextField5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField5ActionPerformed(evt);
			}
		});

		jLabel8.setText("Welcome to helicopter booking system");

		jLabel9.setText("Please choose current location");

		jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"Camp", "Town" }));
		jComboBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox2ActionPerformed(evt);
			}
		});

		jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
				"ACT13", "ACT17", "ATC15", "ATC11", "BCT16", "BCT20", "BTC18",
				"BTC14", "CCT10", "CCT14", "CTC12", "CTC08" }));

		jTable1.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null } },
				new String[] { "Title 1", "Title 2", "Title 3", "Title 4" }));
		jScrollPane3.setViewportView(jTable1);

		jScrollPane3.setBounds(0, 0, 454, 404);
		jDesktopPane1.add(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

		jLabel11.setText("Understand the FlightNum");

		jLabel12.setText("A");

		jLabel13.setText("T");

		jLabel14.setText("Company A");

		jLabel15.setText("LeftTime13:00");

		jLabel18.setText("To Town");

		jLabel19.setText("From Camp");

		jLabel20.setText("13");

		jLabel21.setText("C");

		jLabel10.setText("Powed By Cong.Wang");

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
				.add(layout
						.createSequentialGroup()
						.addContainerGap()
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.LEADING)
								.add(layout
										.createSequentialGroup()
										.add(jLabel3,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												79,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING)
												.add(jLabel4,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														132,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(layout
														.createSequentialGroup()
														.add(jTextField2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																160,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jLabel5)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.UNRELATED)
														.add(jTextField3,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																87,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE).add(jLabel16))
								.add(layout
										.createSequentialGroup()
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING)
												.add(layout
														.createSequentialGroup()
														.add(jLabel9,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																198,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jComboBox2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																138,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
												.add(jLabel8))
										.add(18, 18, 18)
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING)
												.add(layout
														.createSequentialGroup()
														.add(jLabel14)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED))
												.add(org.jdesktop.layout.GroupLayout.TRAILING,
														layout.createSequentialGroup()
																.add(jLabel12)
																.add(35, 35, 35)))
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING)
												.add(jLabel11)
												.add(layout
														.createSequentialGroup()
														.add(layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.TRAILING)
																.add(layout
																		.createSequentialGroup()
																		.add(1,
																				1,
																				1)
																		.add(jLabel19)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.UNRELATED)
																		.add(jLabel18,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED))
																.add(layout
																		.createSequentialGroup()
																		.add(0,
																				0,
																				Short.MAX_VALUE)
																		.add(jLabel21)
																		.add(65,
																				65,
																				65)
																		.add(jLabel13)
																		.add(37,
																				37,
																				37)))
														.add(layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.LEADING)
																.add(layout
																		.createSequentialGroup()
																		.add(jLabel15)
																		.addContainerGap())
																.add(org.jdesktop.layout.GroupLayout.TRAILING,
																		layout.createSequentialGroup()
																				.add(jLabel20)
																				.add(44,
																						44,
																						44))))))
								.add(layout
										.createSequentialGroup()
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING)
												.add(layout
														.createSequentialGroup()
														.add(jButton1)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.UNRELATED)
														.add(jScrollPane1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																362,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
												.add(layout
														.createSequentialGroup()
														.add(jLabel1)
														.add(18, 18, 18)
														.add(jComboBox1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																165,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(32, 32, 32)
														.add(jLabel2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																108,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.UNRELATED)
														.add(jComboBox3,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																117,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
												.add(layout
														.createSequentialGroup()
														.add(jLabel6,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																122,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jTextField4,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																221,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(18, 18, 18)
														.add(jLabel7,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																84,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(jTextField5,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																91,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
												.add(layout
														.createSequentialGroup()
														.add(jButton2)
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.UNRELATED)
														.add(jScrollPane2,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																364,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(84, Short.MAX_VALUE))
								.add(org.jdesktop.layout.GroupLayout.TRAILING,
										layout.createSequentialGroup()
												.add(0, 0, Short.MAX_VALUE)
												.add(jDesktopPane1,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
								.add(jSeparator1)))
				.add(layout
						.createSequentialGroup()
						.add(552, 552, 552)
						.add(jLabel10,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE).addContainerGap()));
		layout.setVerticalGroup(layout
				.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
				.add(layout
						.createSequentialGroup()
						.add(jDesktopPane1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.LEADING)
								.add(layout
										.createSequentialGroup()
										.add(jLabel8,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												27,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jComboBox2,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(163, 163, 163).add(jLabel16))
								.add(layout
										.createSequentialGroup()
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING)
												.add(layout
														.createSequentialGroup()
														.add(40, 40, 40)
														.add(jLabel9,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																14,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
												.add(layout
														.createSequentialGroup()
														.add(layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.TRAILING)
																.add(jLabel12)
																.add(org.jdesktop.layout.GroupLayout.LEADING,
																		layout.createSequentialGroup()
																				.add(jLabel11)
																				.addPreferredGap(
																						org.jdesktop.layout.LayoutStyle.RELATED)
																				.add(layout
																						.createParallelGroup(
																								org.jdesktop.layout.GroupLayout.BASELINE)
																						.add(jLabel13)
																						.add(jLabel20)
																						.add(jLabel21))))
														.addPreferredGap(
																org.jdesktop.layout.LayoutStyle.RELATED)
														.add(layout
																.createParallelGroup(
																		org.jdesktop.layout.GroupLayout.BASELINE)
																.add(jLabel14)
																.add(jLabel19)
																.add(jLabel18,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																		16,
																		org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																.add(jLabel15))))
										.add(25, 25, 25)
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.BASELINE)
												.add(jComboBox3,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(jLabel2)
												.add(jLabel1)
												.add(jComboBox1,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														27,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.UNRELATED)
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.BASELINE)
												.add(jLabel5)
												.add(jTextField3,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
												.add(jLabel3)
												.add(jTextField2,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(jLabel4,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												16,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.add(1, 1, 1)
										.add(layout
												.createParallelGroup(
														org.jdesktop.layout.GroupLayout.LEADING)
												.add(jButton1)
												.add(jScrollPane1,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
														68,
														org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jSeparator1,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.add(5, 5, 5)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.BASELINE)
								.add(jTextField4,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										28,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jLabel6,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										22,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
								.add(jLabel7)
								.add(jTextField5,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.add(layout
								.createParallelGroup(
										org.jdesktop.layout.GroupLayout.LEADING)
								.add(jButton2)
								.add(jScrollPane2,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
										64,
										org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(
								org.jdesktop.layout.LayoutStyle.RELATED)
						.add(jLabel10).addContainerGap()));

		jTextField2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField1ActionPerformed(evt);
			}
		});
		jTextField3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextField3ActionPerformed(evt);
			}
		});
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});
		jComboBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox1ActionPerformed(evt);
			}
		});
		jComboBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox2ActionPerformed(evt);
			}
		});
		jComboBox3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox3ActionPerformed(evt);
			}
		});

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField4ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField4ActionPerformed

	private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField2ActionPerformed

	private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox2ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jComboBox2ActionPerformed

	private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextField5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextField5ActionPerformed

	private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (jComboBox2.getSelectedItem().equals("Camp")) {
			if (jComboBox1.getSelectedItem().equals("CompanyA")) {

				HelicopterClient hc = new HelicopterClient("127.0.0.1", 3000);
				String s1 = (String) jComboBox3.getSelectedItem();
				String s2 = jTextField2.getText();
				String s3 = jTextField3.getText();
				String s = "!" + s1 + "?" + s2 + "*" + s3;
				String r = hc.bookTicket(s);
				jTextArea1.setText(r);
			} else if (jComboBox1.getSelectedItem().equals("CompanyB")) {
				HelicopterClient hc = new HelicopterClient("127.0.0.1", 3000);
				String s1 = (String) jComboBox3.getSelectedItem();
				String s2 = jTextField2.getText();
				String s3 = jTextField3.getText();
				String s = "!" + s1 + "?" + s2 + "*" + s3;
				String r = hc.bookTicket(s);
				jTextArea1.setText(r);
			} else {
				HelicopterClient hc = new HelicopterClient("127.0.0.1", 3000);
				String s1 = (String) jComboBox3.getSelectedItem();
				String s2 = jTextField2.getText();
				String s3 = jTextField3.getText();
				String s = "!" + s1 + "?" + s2 + "*" + s3;
				String r = hc.bookTicket(s);
				jTextArea1.setText(r);
			}
		} else {
			if (jComboBox1.getSelectedItem().equals("CompanyA")) {

				HelicopterClient hc = new HelicopterClient("127.0.0.1", 8000);
				String s1 = (String) jComboBox3.getSelectedItem();
				String s2 = jTextField2.getText();
				String s3 = jTextField3.getText();
				String s = "!" + s1 + "?" + s2 + "*" + s3;
				String r = hc.bookTicket(s);
				jTextArea1.setText(r);
			} else if (jComboBox1.getSelectedItem().equals("CompanyB")) {
				HelicopterClient hc = new HelicopterClient("127.0.0.1", 8000);
				String s1 = (String) jComboBox3.getSelectedItem();
				String s2 = jTextField2.getText();
				String s3 = jTextField3.getText();
				String s = "!" + s1 + "?" + s2 + "*" + s3;
				String r = hc.bookTicket(s);
				jTextArea1.setText(r);
			} else {
				HelicopterClient hc = new HelicopterClient("127.0.0.1", 8000);
				String s1 = (String) jComboBox3.getSelectedItem();
				String s2 = jTextField2.getText();
				String s3 = jTextField3.getText();
				String s = "!" + s1 + "?" + s2 + "*" + s3;
				String r = hc.bookTicket(s);
				jTextArea1.setText(r);
			}
		}

	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (jComboBox2.getSelectedItem().equals("Camp")) {
			if (jComboBox1.getSelectedItem().equals("CompanyA")) {

				HelicopterClient hc = new HelicopterClient("127.0.0.1", 3000);

				String s1 = jTextField4.getText();
				String s2 = jTextField5.getText();
				String s = s1 + "?" + s2;
				String r = hc.cancelFlight(s);
				jTextArea2.setText(r);
			} else if (jComboBox1.getSelectedItem().equals("CompanyB")) {
				HelicopterClient hc = new HelicopterClient("127.0.0.1", 3000);
				String s1 = jTextField4.getText();
				String s2 = jTextField5.getText();
				String s = s1 + "?" + s2;
				String r = hc.cancelFlight(s);
				jTextArea2.setText(r);
			} else {
				HelicopterClient hc = new HelicopterClient("127.0.0.1", 3000);
				String s1 = jTextField4.getText();
				String s2 = jTextField5.getText();
				String s = s1 + "?" + s2;
				String r = hc.cancelFlight(s);
				jTextArea2.setText(r);
			}
		} else {
			if (jComboBox1.getSelectedItem().equals("CompanyA")) {

				HelicopterClient hc = new HelicopterClient("127.0.0.1", 8000);

				String s1 = jTextField4.getText();
				String s2 = jTextField5.getText();
				String s = s1 + "?" + s2;
				String r = hc.cancelFlight(s);
				jTextArea2.setText(r);
			} else if (jComboBox1.getSelectedItem().equals("CompanyB")) {
				HelicopterClient hc = new HelicopterClient("127.0.0.1", 8000);
				String s1 = jTextField4.getText();
				String s2 = jTextField5.getText();
				String s = s1 + "?" + s2;
				String r = hc.cancelFlight(s);
				jTextArea2.setText(r);
			} else {
				HelicopterClient hc = new HelicopterClient("127.0.0.1", 8000);
				String s1 = jTextField4.getText();
				String s2 = jTextField5.getText();
				String s = s1 + "?" + s2;
				String r = hc.cancelFlight(s);
				jTextArea2.setText(r);
			}
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				new UI().setVisible(true);
			}
		});
	}

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JComboBox jComboBox1;
	private javax.swing.JComboBox jComboBox2;
	private javax.swing.JComboBox jComboBox3;
	private javax.swing.JDesktopPane jDesktopPane1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel18;
	private javax.swing.JLabel jLabel19;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JTable jTable1;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextArea jTextArea2;
	private javax.swing.JTextField jTextField2;
	private javax.swing.JTextField jTextField3;
	private javax.swing.JTextField jTextField4;
	private javax.swing.JTextField jTextField5;
	// End of variables declaration//GEN-END:variables
}